package com.gridgain.bitset.model;

import java.io.Serializable;

/**
 * DeviceKey definition.
 * 
 * This file was generated by Ignite Web Console (09/08/2020, 16:10)
 **/
public class DeviceKey implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for id. */
    private Integer id;

    /** Empty constructor. **/
    public DeviceKey() {
        // No-op.
    }

    /** Full constructor. **/
    public DeviceKey(Integer id) {
        this.id = id;
    }

    /**
     * Gets id
     * 
     * @return Value for id.
     **/
    public Integer getId() {
        return id;
    }

    /**
     * Sets id
     * 
     * @param id New value for id.
     **/
    public void setId(Integer id) {
        this.id = id;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof DeviceKey))
            return false;
        
        DeviceKey that = (DeviceKey)o;

        if (id != null ? !id.equals(that.id) : that.id != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = id != null ? id.hashCode() : 0;

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "DeviceKey [" + 
            "id=" + id +
        "]";
    }
}