package com.gridgain.bitset.model_v3;

import java.io.Serializable;

/**
 * DeviceKey definition.
 * 
 * This file was generated by Ignite Web Console (09/08/2020, 16:10)
 **/
public class DeviceKey implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for id. */
    private Integer id;

    /** Value for manufacturerId. */
    private String manufacturerId;

    /** Empty constructor. **/
    public DeviceKey() {
        // No-op.
    }

    /** Migration constructor. **/
    public DeviceKey(com.gridgain.bitset.model.DeviceKey oDeviceKey) {
        this.manufacturerId = "MigratedEmptyMfg";
        this.id = oDeviceKey.getId();
    }

    /** Full constructor. **/
    public DeviceKey(Integer id, String manufacturerId) {
        this.manufacturerId = manufacturerId;
        this.id = id;
    }

    /**
     * Gets id
     * 
     * @return Value for id.
     **/
    public Integer getId() {
        return id;
    }

    /**
     * Sets id
     * 
     * @param id New value for id.
     **/
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Gets manufacturerId
     * 
     * @return Value for manufacturerId.
     **/
    public String getManufacturerId() {
        return manufacturerId;
    }

    /**
     * Sets manufacturerId
     * 
     * @param manufacturerId New value for manufacturerId.
     **/
    public void setManufacturerId(String manufacturerId) {
        this.manufacturerId = manufacturerId;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof DeviceKey))
            return false;
        
        DeviceKey that = (DeviceKey)o;

        if (id != null ? !id.equals(that.id) : that.id != null)
            return false;
        
        if (manufacturerId != null ? !manufacturerId.equals(that.manufacturerId) : that.manufacturerId != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = id != null ? id.hashCode() : 0;

        res = 31 * res + (manufacturerId != null ? manufacturerId.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "DeviceKey [" + 
            "id=" + id +
            "manufacturerId=" + manufacturerId +
        "]";
    }
}